# Generated by Django 2.2 on 2022-01-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quant',
            new_name='quan',
        ),
    ]
